---
- name: Create role working dir
  ansible.builtin.file:
    path: "{{ soapui_role_working_dir }}"
    state: directory
    mode: 'u=rwx,go=rx'
  become: true

- name: Download SoapUI
  ansible.builtin.get_url:
    url: "{{ soapui_url }}"
    dest: "{{ soapui_role_working_dir }}"
    mode: 0777
  register: downloaded_file
  become: true

- name: Install SoapUI
  ansible.builtin.command: "{{ downloaded_file.dest }} -dir {{ soapui_install_dir }} -q"
  register: installation_command
  changed_when: false
  become: true

- name: Find all SoapUI desktop files
  ansible.builtin.find:
    paths: /usr/share/applications,/usr/local/share/applications
    file_type: file
    patterns: "*SoapUI-{{ soapui_version }}*.desktop"
  register: desktop_files
  become: true

- name: Replace category application with development
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: 'Categories=Application;'
    replace: 'Categories=Development;'
  with_items: "{{ desktop_files.files }}"
  become: true
