---
- name: Uninstall SoapUI
  ansible.builtin.command: "{{ soapui_install_dir }}/uninstall -q"
  changed_when: false
  become: true

- name: Find all SoapUI desktop files
  ansible.builtin.find:
    paths: /usr/share/applications,/usr/local/share/applications
    file_type: file
    patterns: "*SoapUI-{{ soapui_version }}*.desktop"
  register: desktop_files
  become: true

- name: Remove all SoapUI desktop files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ desktop_files.files }}"
  become: true
